# Generated by Django 3.0.5 on 2020-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaridpurDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_cases', models.CharField(max_length=20, null=True)),
                ('new_cases', models.CharField(max_length=20, null=True)),
                ('total_deaths', models.CharField(max_length=20, null=True)),
                ('new_deaths', models.CharField(max_length=20, null=True)),
                ('total_recovered', models.CharField(max_length=20, null=True)),
                ('active_cases', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GazipurDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_cases', models.CharField(max_length=20, null=True)),
                ('new_cases', models.CharField(max_length=20, null=True)),
                ('total_deaths', models.CharField(max_length=20, null=True)),
                ('new_deaths', models.CharField(max_length=20, null=True)),
                ('total_recovered', models.CharField(max_length=20, null=True)),
                ('active_cases', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GopalganjDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_cases', models.CharField(max_length=20, null=True)),
                ('new_cases', models.CharField(max_length=20, null=True)),
                ('total_deaths', models.CharField(max_length=20, null=True)),
                ('new_deaths', models.CharField(max_length=20, null=True)),
                ('total_recovered', models.CharField(max_length=20, null=True)),
                ('active_cases', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
