# Generated by Django 3.0.5 on 2020-04-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faridpurdistrict_gazipurdistrict_gopalganjdistrict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GazipurDistrict',
            new_name='CoronaVirus',
        ),
        migrations.DeleteModel(
            name='DhakaDistrict',
        ),
        migrations.DeleteModel(
            name='FaridpurDistrict',
        ),
        migrations.DeleteModel(
            name='GopalganjDistrict',
        ),
    ]
