# Generated by Django 3.0.5 on 2020-04-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200409_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronavirus',
            old_name='name',
            new_name='district_name',
        ),
    ]
