# Generated by Django 3.0.5 on 2020-04-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200409_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronavirus',
            old_name='district_name',
            new_name='name',
        ),
    ]
