# Generated by Django 3.0.5 on 2020-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200409_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaCasess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.CharField(max_length=200, null=True)),
                ('recovered', models.CharField(max_length=200, null=True)),
                ('deaths', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
