# Generated by Django 3.0.5 on 2020-04-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coronacasess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoronaCasess',
            new_name='CoronaCases',
        ),
    ]
