# Generated by Django 3.0.5 on 2020-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200409_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacases',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
