# Generated by Django 3.0.5 on 2020-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_coronacases_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacases',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
